# 机场三字码 -> 中文名称映射
AIRPORTS: dict[str, str] = {
    "PEK": "北京首都",
    "PKX": "北京大兴",
    "SHA": "上海虹桥",
    "PVG": "上海浦东",
    "CAN": "广州",
    "SZX": "深圳",
    "CTU": "成都天府",
    "TFU": "成都双流",
    "HAK": "海口",
    "SYX": "三亚",
    "WUH": "武汉",
    "CSX": "长沙",
    "HGH": "杭州",
    "NKG": "南京",
    "XMN": "厦门",
    "FOC": "福州",
    "TAO": "青岛",
    "TNA": "济南",
    "TSN": "天津",
    "DLC": "大连",
    "SHE": "沈阳",
    "HRB": "哈尔滨",
    "CGQ": "长春",
    "XIY": "西安",
    "KMG": "昆明",
    "NNG": "南宁",
    "KWE": "贵阳",
    "KHN": "南昌",
    "CGO": "郑州",
    "TYN": "太原",
    "SJW": "石家庄",
    "HFE": "合肥",
    "NGB": "宁波",
    "WNZ": "温州",
    "ZUH": "珠海",
    "SWA": "揭阳",
    "URC": "乌鲁木齐",
    "LHW": "兰州",
    "XNN": "西宁",
    "INC": "银川",
    "HET": "呼和浩特",
    "BAV": "包头",
    "WEH": "威海",
    "YNT": "烟台",
    "WUX": "无锡",
    "HYN": "台州",
    "LJG": "丽江",
    "DLU": "大理",
    "TXN": "黄山",
    "ENH": "恩施",
    "ZYI": "遵义",
    "MIG": "绵阳",
    "YIH": "宜昌",
    "JJN": "晋江泉州",
    "CKG": "重庆",
    "KHG": "喀什",
    "AKU": "阿克苏",
    "HLD": "海拉尔",
    "LYA": "洛阳",
    "YLN": "延吉",
}


def airport_name(code: str) -> str:
    """返回机场中文名，未知代码直接返回代码本身。"""
    return AIRPORTS.get(code.upper(), code)
